### ISSUE TITLE
task is not completed

### ISSUE THREAD

**Issue by dzhivushko** [Dasha-V/HomeTask#11]
https://github.com/Dasha-V/HomeTask/blob/85d59d1be29b460c7ee3dc919c16c62eb188c71d/src/by/academy/dv/java/task21/HomeTask21.java#L3-L18
the goal of the task is to calculate a time of functions execution (which of 2 variants is faster). You didn't calculate a time at all

for example
   ```
 public static void main(final String[] args) throws Exception {

        final long timeStringStart = System.currentTimeMillis();

        String str = "";
        for (int i = 0; i <= 10000; i++) {
            str += i;

        }
        final long timeStringEnd = System.currentTimeMillis();

        System.out.println("the final string:" + str);
        System.out.println("spent time:" + (timeStringEnd - timeStringStart));

    }
```

the repeat the same logic with StringBuilder and make the decision which variant of string concat.is faster

**Comment by Dasha-V** [comment]
done
