### ISSUE TITLE
Do not create confusing variable name

### ISSUE THREAD

**Issue by dzhivushko** [Dasha-V/HomeTask#16]
https://github.com/Dasha-V/HomeTask/blob/85d59d1be29b460c7ee3dc919c16c62eb188c71d/src/by/academy/dv/java/task27/HomeTask27.java#L22

do not  write code like 
`Set list=new HashSet()`
it is very confusing. is hope you understand why and how to fix

**Comment by Dasha-V** [comment]
Because it`s dificult to understand what is it list or set
Set<Integer> st= new HashSet<Integer>();
is it ok to write so?

**Comment by dzhivushko** [comment]
Set set= new HashSet();
:+1:
