### ISSUE TITLE
use forEach where possible

### ISSUE THREAD

**Issue by dzhivushko** [Dasha-V/HomeTask#24]
https://github.com/Dasha-V/HomeTask/blob/a4df4d728c51b1d7384edf7d2a4078ec42c2bbff/src/scheduletask/two/ArrCheck.java#L6-L20
for me it looks like 'forEach' can be used in all 3 cases instead of iteration with temporary variable. 
if it is true then use forEach (always when you need to iterate through the whole collection/array)

**Comment by Dasha-V** [comment]
I don't understand how to use forEach here :( I caught the Ecseption when I  tried to use foreach here.

**Comment by dzhivushko** [comment]
```
public class Test {

	public static void main(String[] args) throws Exception {
		int[] arr1 = new int[] { 1, 2, 3, 4, 5, 6 };
		int[] arr2 = new int[] { 3, 4, 56, 6, 2 };
		int[] arr3 = new int[] { 3, 2, 3, 4, 5 };

		for (int a1 : arr1) {
			for (int a2 : arr2) {
				for (int a3 : arr3) {
					int a1a2 = a1 + a2;
					if (a3 == a1a2) {
						System.out.println(a1 + "+" + a2 + " = " + a3);
					}
				}
			}
		}

	}

}
```

**Comment by Dasha-V** [comment]
Thanks a lot!
