### ISSUE TITLE
Illegal classes and constructor usage

### ISSUE THREAD

**Issue by dzhivushko** [Dasha-V/HomeTask#27]
https://github.com/Dasha-V/HomeTask/blob/a4df4d728c51b1d7384edf7d2a4078ec42c2bbff/src/scheduletask/six/TestClass.java#L21-L22

TransportSchedule  do not need 'new' instances of objects which it accepts in constructor.  I have created the issues about it. will not repeat the reason. simply 'do not create classes when you do not need them'. for the first time simply stop creation of classes if they do not have any 'property'

**Comment by Dasha-V** [comment]
I tried to fix all mistakes . I hope successfully. Take a look  at task 5,please. i don't like the result, but I have no variants how to do it better.
