### ISSUE TITLE
invalid class

### ISSUE THREAD

**Issue by dzhivushko** [Dasha-V/HomeTask#28]
https://github.com/Dasha-V/HomeTask/blob/a4df4d728c51b1d7384edf7d2a4078ec42c2bbff/src/scheduletask/ten/Coin.java#L3

Class 'Coin' should represent object 'Coin'. Nothing else.
You can create the class Coin. but it will have coin's properties and coin's behaviour. it is not the same what you did. You created this class to wrap function which executes logic from the task. but this function is not related to the 'coin' object.

**Comment by dzhivushko** [comment]
re-write this task again and let me see if you understand what I mean

**Comment by Dasha-V** [comment]
Hi! in general we don't need this class at all. I just did it for exercise. But I understood. If something has name Coin it must have behavior and characteristics of coin. Now it`s has name Executor and  one method inside. is it ok?

**Comment by dzhivushko** [comment]
i do not see the updated version
