### ISSUE TITLE
do not create the variable before the usage if it is not required

### ISSUE THREAD

**Issue by dzhivushko** [Dasha-V/HomeTask#4]
https://github.com/Dasha-V/HomeTask/blob/386682cb5b9fde7eec27e0b28af5c7734104dc0e/src/by/academy/dv/java/task2/HomeTask2.java#L5-L18

**Comment by dzhivushko** [comment]
it should be
	int s = 605000; 
 	int sec = s% 60; 
 	int m = (s-sec)/60; 
 	int min = m%60; 
 	int h = (m-min)/60;  
        int day = h/24; 
 	int week = day/7;

**Comment by Dasha-V** [comment]
done
